# Generated by Django 4.1.7 on 2023-04-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
