# Generated by Django 4.1.7 on 2023-04-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', 'EUROPEAN CURRENCY'), ('USD', 'UNITED STATES DOLLAR'), ('RUB', 'RUSSIAN ROUBLE'), ('YEN', 'JAPAN CURRENCY'), ('DIR', 'ARABIAN CURRENCY'), ('CAD', 'CANADIAN CURRENCY')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('course', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_exchanger.currency')),
            ],
        ),
    ]
