# Generated by Django 4.1.7 on 2023-05-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EUR', 'EUROPEAN CURRENCY'), ('USD', 'UNITED STATES DOLLAR'), ('RUB', 'RUSSIAN ROUBLE CURRENCY'), ('YEN', 'JAPAN CURRENCY'), ('DIR', 'ARABIAN CURRENCY'), ('CAD', 'CANADIAN CURRENCY'), ('AUD', 'AUSTRALIAN DOLLAR CURRENCY'), ('AZN', 'AZERBAIJANIAN MANAT CURRENCY'), ('BGN', 'BULGARIAN LEV CURRENCY'), ('CZK', 'CZECH KORUNA CURRENCY'), ('DKK', 'DANISH CRONE CURRENCY'), ('EGP', 'EGYPTIAN POUND CURRENCY'), ('JPY', 'JAPANESE YEN CURRENCY')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.DecimalField(decimal_places=4, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='currency_exchanger.currency')),
            ],
        ),
    ]
