# Generated by Django 4.1.7 on 2023-06-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchanger', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
