# Generated by Django 4.1.7 on 2023-05-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchanger', '0002_alter_currency_name_alter_currencyrate_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(choices=[('EUR', 'EUROPEAN CURRENCY'), ('USD', 'UNITED STATES DOLLAR'), ('RUB', 'RUSSIAN ROUBLE CURRENCY'), ('KZT', 'KAZAKHSTAN TENGE CURRENCY'), ('CAD', 'CANADIAN CURRENCY'), ('AUD', 'AUSTRALIAN DOLLAR CURRENCY'), ('AZN', 'AZERBAIJANIAN MANAT CURRENCY'), ('BGN', 'BULGARIAN LEV CURRENCY'), ('CZK', 'CZECH KORUNA CURRENCY'), ('DKK', 'DANISH CRONE CURRENCY'), ('EGP', 'EGYPTIAN POUND CURRENCY'), ('JPY', 'JAPANESE YEN CURRENCY')], max_length=150),
        ),
    ]
