# Generated by Django 4.1.7 on 2023-05-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchanger', '0003_alter_currencyrate_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
